server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ms-cuenta-movimiento

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db_cuenta?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Guayaquil}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: America/Guayaquil

  jackson:
    time-zone: America/Guayaquil
    serialization:
      write-dates-as-timestamps: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

logging:
  level:
    root: INFO
    com.banco: DEBUG
